[package]
name = "dehashed-rs"
edition = "2024"
version = "0.6.0"
repository = "https://github.com/myOmikron/dehashed-rs"
authors = ["Niklas Pfister <git@omikron.dev>"]
license = "MPL-2.0"
description = "A rust library for the dehashed API"


[dependencies]
# HTTP library
reqwest = { version = "~0.12", features = ["json"] }

# Serialization library
serde = { version = "~1", features = ["derive"] }
serde_json = { version = "~1" }

# Logging framework
tracing = { version = "~0.1" }

# Async runtime
tokio = { version = ">=1.23.1", features = ["sync"], optional = true }

# Openapi generator
utoipa = { version = "~4", optional = true }

# Json schema
schemars = { version = "~0.8", optional = true }

[package.metadata.docs.rs]
features = ["tokio", "utoipa", "schemars"]

[dev-dependencies]
tokio = { version = ">=1.23.1", features = ["rt-multi-thread", "macros", "sync"] }
tokio-test = { version = "~0.4" }
tracing-subscriber = { version = "~0.3" }

[features]
default = []
tokio = ["dep:tokio"]
utoipa = ["dep:utoipa"]
schemars = ["dep:schemars"]

[[example]]
name = "simple"

[[example]]
name = "scheduler"
required-features = ["tokio"]
